### ISSUE TITLE
Find a way to detect wrong string interpolation

### ISSUE THREAD

**Issue by pawelprazak** [VirtusLab/besom#146]
It would be helpful to the user if we could detect at compile time this subtle problem:
```
sourceArn = s"${api.executionArn}/*"
```

instead of runtime error:
```
Diagnostics:
  aws:lambda:Permission (feedLambdaPermission):
    error: aws:lambda/permission:Permission resource 'feedLambdaPermission' has a problem: "source_arn" (besom.internal.Output@6da60311/*) is an invalid ARN: arn: invalid prefix. Examine values at 'feedLambdaPermission.sourceArn'.
````

And recommend user to use our interpolator:
```
sourceArn = p"${api.executionArn}/*"
```

This is a very common problem in all other SDKs, so this is a nice-to-have. 
This might not be possible thou.

**Comment by lbialy** [comment]
It's a solved problem (but we don't have docs so I don't blame you): there's a compiler plugin that crashes compile on any s"" interpolation that has an Output passed to it. We were just talking about that with @KacperFKorban who wrote the plugin because there's #108 and we have a problem there regarding which version should be added automatically to besom user program. Once #108 will be done this plugin will be added to user's program (not in sbt set up manually - we can only add it in sbt templates) automagically. I guess this can be closed as #108 tracks the progress on auto-include of the plugin.

**Comment by pawelprazak** [comment]
We should probably document the need for compiler plugin before closing this bug, esp. for non-sbt users, WDYT?

**Comment by KacperFKorban** [comment]
I added a page about the compiler plugin here: https://github.com/VirtusLab/besom/pull/127/files#diff-255f8c5e2df43e2808fbac358cf75dcc97993ee8c73080d1b7cd3d64c47ae0ac
And also a note about using the interpolator here: https://github.com/VirtusLab/besom/pull/127/files#diff-e70b16e12d73c3e8a843e82e841da4447af28c91b4711fb6ee839dc4ad4607aeR17-R23

**Comment by pawelprazak** [comment]
Great, thank you.

Note to self: make sure we have this compiler plugin in our templates!
