### ISSUE TITLE
Add vararg version of `Output.sequence`

### ISSUE THREAD

**Issue by pawelprazak** [VirtusLab/besom#171]
Current API requires following code:
```
dependsOn = Output.sequence(List(feedLambda, addLambda))
```

A varags version would allow for:
```
dependsOn = Output.sequence(feedLambda, addLambda)
```

Open questions:
- is this something a Scala programmer will expect
- are there any better designs (e.g. is `dependsOn = List(feedLambda, addLambda)` possible with some Scala magic)

**Comment by lbialy** [comment]
There are three things here: 
a) whether dependsOn should always expect `Output[List[Resource]]`, maybe the expected type should be improved upon with a union?
b) more general question about argument positions such as dependsOn and their lock to `Output[List[A]]`, maybe there's some room for improvement
c) adding a variadic variant of Output.sequence, this should be quite easy but interestingly it's a bit unexpected. I guess it should be fine because for us it's a static function on `Output` object and not a syntactic extension, eg.: `List(a, b).sequence` which require that List there to work. I'll have to ask somebody from cats/zio why there are no variadic variants because I worry there might be an unexpected issue with that.

**Comment by lbialy** [comment]
a) and b) are done in #355 c) can be added

**Comment by pawelprazak** [comment]
regarding c) let's leave the varargs out and come back to this idea if there is a strong signal from the community that this is something that is needed, WDYT?
