### ISSUE TITLE
Logging doesn't seem to do anything

### ISSUE THREAD

**Issue by note** [VirtusLab/besom#308]
I am following https://github.com/VirtusLab/besom/blob/develop/examples/aws-webserver/Main.scala

It works just fine, with the exception of logging. I am not well versed in Pulumi, but none of `log.warn`, `log.info` or `log.error` has any effect on the output at all. I even tried with `pulumi up -v=10 --logtostderr`, but still with no luck.

To be more precise, I am using the code from the mentioned example, with slight modification in the main `for`:

```scala
for {
    server: ec2.Instance <- server
    _                    <- sshKey
    _                    <- keyPair
    _                    <- log.warn("Anything WARN")
    _                    <- log.error("Anything ERROR")
    _                    <- p"Connect to SSH the first time: pulumi stack output privateKey --show-secrets > key_rsa && chmod 400 key_rsa && ssh -i key_rsa ${userName}@${server.publicIp}".map(log.info(_))
    _                    <- log.info("Connect to SSH: ssh -i key_rsa ec2-user@$(pulumi stack output publicIp)")
    _                    <- log.info("Connect to HTTP: open http://$(pulumi stack output publicHostName)")
  } yield Pulumi.exports(
    publicKey = publicKey,
    privateKey = privateKey,
    publicIp = server.publicIp,
    publicHostName = server.publicDns,
  )
```

So that rules out the possibility of unused `Output`

**Comment by lbialy** [comment]
That's sadly true in 0.1.0. There's a very tricky bug related to dispatch on overridden methods in BesomLogger implementation. That logger sends all logs to two sinks, a grpc based Pulumi engine one and a normal file based one. Due to aforementioned bug in 0.1.0 only sink to receive logs is the file one. This is fixed in develop but not released yet. You can enable file logging though using PULUMI_ENABLE_TRACE_LOGGING_TO_FILE env variable set to true.

Sorry!

**Comment by note** [comment]
Thanks for the update!

**Comment by lbialy** [comment]
Release of 0.2.0 that publishes fix for this problem is now underway. Closing the issue.
