### ISSUE TITLE
Is colon allowed in resourceName?

### ISSUE THREAD

**Issue by dubinsky** [VirtusLab/besom#387]
As a part of https://github.com/VirtusLab/besom/pull/328, `besom.URN.UrnRegex` changed, including the change from `(?<resourceName>.+)` to `(?<resourceName>[^:]+|[^:]*::[^:]*)`.

With this change, URNs that contain a single colon `:` in the `resourceName` (e.g., `group:info`) became illegal, although the comment in the code suggests that they should remain legal:
```
Stack, Project, and Name Regex: These are strings that do not contain ::.
```
Was this change intentional?

Thanks!

**Comment by lbialy** [comment]
Possibly a mistake, let me investigate, we have few quick patches that are coming out very soon in 0.2.1 (core only, packages won't need to be republished, hence the change in versioning scheme for packages with patch version dropped).

**Comment by lbialy** [comment]
We are obviously not going to follow that folly to the letter. Empty strings make absolutely no sense for Stack names, Project names and Resource names. However, Pulumi's test suite does test against an URN with empty resource name. We are going to allow any garbage in resource names, including empty strings, if that's something that comes from the engine but still require non-empty strings that adhere to the spec from our users because why propagate a mistake.

**Comment by dubinsky** [comment]
> anything is permitted as a resource name in Pulumi since November
> require non-empty strings that adhere to the spec from our users

I am pretty sure that colon was allowed in the resource name even before November;
thank you for fixing it soon!

**Comment by lbialy** [comment]
I got tests green few minutes ago, adding cases to catch garbage in compile
time but allow garbage when coming from the wire :shrug:
